name: 'gemini-code-reviewer'
description: 'gemini llm code reviewer'

inputs:
  pr_number:
    description: 'PR/Issue 번호'
    required: true
  repo:
    description: '저장소 이름'
    required: true
  owner:
    description: '저장소 소유자'
    required: true
  gemini_api_key:
    description: 'gemini api 키'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: get pr diff
      id: diff
      uses: actions/github-script@v7
      env:
        PR_NUMBER: ${{ inputs.pr_number }}
        REPO_OWNER: ${{ inputs.owner }}
        REPO_NAME: ${{ inputs.repo }}
      with:
        script: |
          const result = await github.rest.pulls.get({
            pull_number: Number(process.env.PR_NUMBER),
            owner: process.env.REPO_OWNER,
            repo: process.env.REPO_NAME,
            headers: {
              accept : 'application/vnd.github.v3.diff'
            }
          })

          const prDiff = result.data;

          console.log(result.data);

          return prDiff;
    - name: gemini pr review request
      id: review
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        RAW_DIFF: ${{ steps.diff.outputs.result }}
      run: |
        PROMPT='다음 PR 내용 요약해줘\n\n ${{ env.RAW_DIFF }}'

        REQUEST_BODY=(jq -n --arg diff "$PROMPT" '{
          contents: [{
            parts: [{ text: $diff }]
          }]
        }')

        RESULT=$(curl -s curl --location --request POST 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent' \
          --header 'x-goog-api-key: ${{ env.GEMINI_API_KEY }}' \
          --header 'Content-Type: application/json' \
          --header 'Accept: */*' \
          --header 'Host: generativelanguage.googleapis.com' \
          --data-raw "$REQUEST_BODY"
          )

        echo $RESULT
        echo $RESULT >> $GITHUB_OUTPUT
    - name: write comment
      shell: bash
      run: |
        echo ${{ steps.review.outputs.result }}