name: 'gemini-code-reviewer'
description: 'gemini llm code reviewer'

inputs:
  pr_number:
    description: 'PR/Issue 번호'
    required: true
  repo:
    description: '저장소 이름'
    required: true
  owner:
    description: '저장소 소유자'
    required: true
  gemini_api_key:
    description: 'gemini api 키'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: get pr diff
      id: diff
      uses: actions/github-script@v7
      env:
        PR_NUMBER: ${{ inputs.pr_number }}
        REPO_OWNER: ${{ inputs.owner }}
        REPO_NAME: ${{ inputs.repo }}
      with:
        script: |
          const result = await github.rest.pulls.get({
            pull_number: Number(process.env.PR_NUMBER),
            owner: process.env.REPO_OWNER,
            repo: process.env.REPO_NAME,
            headers: {
              accept : 'application/vnd.github.v3.diff'
            }
          })

          const prDiff = result.data;

          console.log(result.data);

          return prDiff;
    - name: gemini pr review request
      id: request-review
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        RAW_DIFF: ${{ steps.diff.outputs.result }}
      run: |
        PROMPT='다음 PR 내용 요약해줘. 응답은 3단계로 나누어서 해줘. 1. PR 요약 2. PR 리뷰 3. 참고 참고의 경우에는 너의 모델명만 짧게 언급해줘  \n\n ${{ env.RAW_DIFF }}'

        REQUEST_BODY=$(jq -n --arg diff "$PROMPT" '{
          contents: [{
            parts: [{ text: $diff }]
          }]
        }')

        RESPONSE=$(curl -s curl --location --request POST 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent' \
          --header 'x-goog-api-key: ${{ env.GEMINI_API_KEY }}' \
          --header 'Content-Type: application/json' \
          --header 'Accept: */*' \
          --header 'Host: generativelanguage.googleapis.com' \
          --data-raw "$REQUEST_BODY"
          )

        # 2. JSON 응답에서 실제 리뷰 텍스트만 추출 (jq 사용)
          # .candidates[0].content.parts[0].text 경로의 값을 가져옵니다.
        REVIEW_RESULT=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')

        # 3. 멀티라인 텍스트를 GITHUB_OUTPUT에 안전하게 저장
          {
            echo "result<<EOF"
            echo "$REVIEW_RESULT"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
    - name: write comment
      uses: actions/github-script@v7
      env:
        PR_NUMBER: ${{ inputs.pr_number }}
        REPO_OWNER: ${{ inputs.owner }}
        REPO_NAME: ${{ inputs.repo }}
        REVIEW_RESULT : ${{ steps.request-review.outputs.result }}
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: Number(process.env.PR_NUMBER),
            owner: process.env.REPO_OWNER,
            repo: process.env.REPO_NAME,
            body: process.env.REVIEW_RESULT
          })