name: usesTest
on: 
  pull_request_review_comment:
    types: [created]
jobs: 
  comment:
    name: comment hello world
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Dump GitHub context
        run: echo "${{ toJSON(github.event) }}"