name: pull-request-comment
inputs:
  issue_number:
    type: number
    required: true
  repo:
    type: string
    required: true
  owner:
    type: string
    required: true

jobs: 
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo "${{ toJSON(github.event) }}"
      - name: Post hello world comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{inputs.issue_number}},
              owner: ${{ inputs.owner }},
              repo: ${{ inputs.repo }},
              body: 'hello world'
            })