name: uses
on: 
  issue_comment:
    types: [created]

jobs: 
  comment:
    if: github.event.issue.pull_request && github.event.comment.body == 'please comment'
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo "${{ toJSON(github.event) }}"
      - name: Post hello world comment
        uses: './.github/workflows/pull-request-comment'
        with:
          issue_number: ${{ github.event.issue.number }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}