name: uses
on: 
  issue_comment:
    types: [created]

jobs: 
  comment:
    if: github.event.issue.pull_request && github.event.comment.body == 'please comment'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Post hello world comment
      uses: './.github/actions/pull-request-comment'
      with:
        issue_number: context.issue.number
        owner: context.repo.owner
        repo: context.repo.repo